Fix some hlint warnings - part 2
haskell/hackage-server pull request #1057
Opened 2022-04-13 12:42 UTC by jhrcek

Second batch of hopefully non-controversial hlint fixes (as discussed in https://github.com/haskell/hackage-server/pull/1056#issuecomment-1097855098).

2022-04-13 12:43 UTC, jhrcek commented on src/Distribution/Server/Features/BuildReports/BuildReports.hs
> +newtype BuildReports = BuildReports {
Of all the "use newtype" suggestions I only applied those where the unrerlying field was strict, so as not to change strictness properties of any of the single-constructor single-field datatypes.

2022-04-13 13:25 UTC, andreasabel requested changes
I would abstain from the `data -> newtype` conversions. (see my comment)
Everything else has my 100% approval!

2022-04-13 13:53 UTC, jhrcek commented on src/Distribution/Server/Features/BuildReports/BuildReports.hs
> +newtype BuildReports = BuildReports {
Ok, makes sense. All the newtype changes reverted.

2022-04-15 09:32 UTC, jhrcek commented
@andreasabel friendly ping :smile_cat:

2022-04-15 15:30 UTC, gbaz approved these changes

2022-04-15 15:30 UTC, merged

2022-04-16 05:29 UTC, andreasabel reviewed
Thanks for update!  Approved!