Add uploaded at field in package api
haskell/hackage-server pull request #1080
Opened 2022-05-22 21:22 UTC by Kleidukos

At present time, the information returned by the Package JSON API amounts to:

```json
{
    "author": "Hécate Moonlight",
    "copyright": "",
    "description": "The 'Display' typeclass provides a solution for user-facing output that does not have to abide by the rules of the Show typeclass.",
    "homepage": "https://github.com/haskell-text/text-display#readme",
    "license": "MIT",
    "metadata_revision": 0,
    "synopsis": "A typeclass for user-facing output"
}
```

This PR aims to implement support for the package upload timestamp in this payload.

2022-05-22 22:45 UTC, Kleidukos commented
@gbaz I tried to make the changes as less invasive as possible. Is there something that should be improved?

2022-05-23 06:32 UTC, andreasabel requested changes
Looks reasonable!, just cosmetical changes requested.

2022-05-23 06:32 UTC, andreasabel commented on src/Distribution/Server/Features/PackageInfoJSON.hs
> +      pbd_uploaded_at = uploadedAt
Follow indentation scheme of lines above.

2022-05-23 06:32 UTC, andreasabel commented on src/Distribution/Server/Features/PackageInfoJSON/State.hs
> +  , pbd_uploaded_at  :: !UTCTime
ditto

2022-05-23 06:32 UTC, andreasabel commented on src/Distribution/Server/Features/PackageInfoJSON/State.hs
> +        pbd_uploaded_at <- safeGet
ditto

2022-05-23 06:32 UTC, andreasabel commented on src/Distribution/Server/Features/PackageInfoJSON/State.hs
> +        pbd_uploaded_at  <- obj .: Key.fromString "uploaded_at"
ditto

2022-05-23 07:37 UTC, Kleidukos commented
Annex question: I'm not super clear on how information is stored, and especially the download numbers. I'd like to expose that kind of information in a subsequent PR.

2022-05-23 17:08 UTC, andreasabel approved these changes
Great, thanks!

2022-05-31 15:56 UTC, Kleidukos commented
@gbaz soft-ping

2022-06-07 15:39 UTC, merged

2022-06-07 15:40 UTC, andreasabel commented
This PR looks reasonable and I do not expect it to break something, so I dared to merge it.  @gbaz, please revert if you disagree.