List maintainers on package page
haskell/hackage-server pull request #1098
Opened 2022-07-10 15:10 UTC by AliasQli

This pull request implements issue #637 as a gsoc project mentored by @gbaz. It displays hackage maintainers in Maintainer's Corner, on both package and candidate pages. Looks like this:

![4](https://user-images.githubusercontent.com/42169770/178150654-17ece2b9-2018-4f8b-917b-59c0ff6039de.png)

2022-07-14 08:41 UTC, andreasabel commented on src/Distribution/Server/Pages/Group.hs
> +  where displayName uname = (anchor ! [href $ "/user/" ++ display uname] << display uname)
The last line has copy-and-paste code from above.  Please factor out the common code.

2022-07-14 08:41 UTC, andreasabel requested changes
Some changes requested (see above).

2022-07-14 11:43 UTC, AliasQli commented
> Is _Maintainers_ identical to _package maintainers_?

Yes. However, I don't understand what you mean by "the same terminology". Did you mean moving these links to the *Maintainers* section in the right?

2022-07-14 13:28 UTC, gbaz commented
As Alias says, the "maintainer" field on the right is a free text field in the cabal file. This "maintainers" is the listing of actual hackage accounts with maintainer rights for the package. So I think it should live where it does, and not on the right. We could rename this new one to "hackage maintainers" or "hackage maintainers group" or something more clarifying...

2022-07-15 08:14 UTC, andreasabel commented
All I meant is:
```
MAINTAINERS (linking to the hackage maintainers pages): Alice, Bob, Carlo
For MAINTAINERS and hackage trustees
* edit package information
```
Here, replace MAINTAINERS by either "maintainers" or "package maintainers", but use the same wording; otherwise one could think that different collections of individuals are meant there.
Put the link on the first occurrence of MAINTAINERS rather than on the second.

2022-07-15 08:36 UTC, andreasabel approved these changes

2022-07-15 08:37 UTC, AliasQli commented
![image](https://user-images.githubusercontent.com/42169770/179185117-1d3abc62-70d2-4f43-9e4c-a76edda5825e.png)
Now this looks fine.

2022-12-30 22:14 UTC, merged

2023-04-13 05:00 UTC, andreasabel commented
Closes #637. Closes #953.